environment:
    matrix:
      - COMPILER: Visual Studio 14 2015
        GENERATOR: "Visual Studio 14 2015"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

      - COMPILER: Visual Studio 15 2017
        GENERATOR: "Visual Studio 15 2017"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

      - COMPILER: MinGW 5
        GENERATOR: "MinGW Makefiles"
        BINDIR: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

      - COMPILER: MinGW 6
        GENERATOR: "MinGW Makefiles"
        BINDIR: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

configuration:
  - Debug

before_build:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if defined BINDIR (set "PATH=%BINDIR%;%PATH%")

  - set "SOURCE_PATH=%APPVEYOR_BUILD_FOLDER%"

  - set "BUILD_PATH=%APPVEYOR_BUILD_FOLDER%\build"
  - mkdir "%BUILD_PATH%"

  - set "INSTALL_PATH=%APPVEYOR_BUILD_FOLDER%\install"
  - mkdir "%INSTALL_PATH%"

  - set "CMAKE_ARGS=%SOURCE_PATH% -DTINYREFL_BUILD_TESTS=ON -DTINYREFL_BUILD_EXAMPLES=ON"
  - if defined GENERATOR (set "CMAKE_ARGS=%CMAKE_ARGS% -G"%GENERATOR%"")
  - set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIGURATION%"

  - cmake --version
  - echo cmake %CMAKE_ARGS%
  - pushd "%BUILD_PATH%" && cmake %CMAKE_ARGS% & popd

build_script:
    pushd "%BUILD_PATH%" && ctest -C "%CONFIGURATION%" --output-on-failure -E "^test.(format|header)" & popd
    tool/tinyrefl_example.exe